version: "3.2"

services:
  api:
    container_name: api
    image: api
    build: api
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
